### ISSUE TITLE
Wrong URL in Vagrantfile

### ISSUE THREAD

**Issue by TineRobbe** [thedatahub/Datahub-Box#2]
I use Mac OS Sierra. The URL to the built Vagrant box in the Vagrantfile can't be found. There seems to be a problem with this line in the Vagrantfile:

`config.vm.box_url = "file://packer/build/datahub-trusty64.box"`

**Comment by nvanderperren** [comment]
Are you in the root directory of the project? I had the same problem when I used the vagrant-command in the packer directory.

After cd-ing to the root directory of the project folder, datahub-trusty64 was successfully added.

**Comment by netsensei** [comment]
Correct. You have to 'cd' in the root of the project, where the Vagrantfile resides, before executing vagrant up. Vagrant will use the current working directory (cwd) as the root path against which it tries to find the box file.

Cleaning out old issues with no follow up. Closing this.
