### ISSUE TITLE
Environment variables should be loaded into Vagrantfile via YAML config

### ISSUE THREAD

**Issue by nvanderperren** [thedatahub/Datahub-Box#7]
I've got this error message:

> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> vm:
> * The host path of the shared folder is missing: /Users/matthiasvandermaesen/Workspace/datahub

Do I need to change something in the vagrantfile?

**Comment by pieterdp** [comment]
Yes - you must replace 'matthiasvandermaesen' with your own Username ;-)

**Comment by netsensei** [comment]
Currently, the vagrantfile contains environment specific values. Such as the path to the shared folder. 

The vagrantfile is actually a Ruby file which gets executed on `vagrant up`. As such, it's possible to add code which could read those specific values from a separate configuration file and interpolate them in the Vagrantfile itself at runtime.

* [Example one](http://juliangut.com/blog/configure-vagrant-hosts-yaml)
* [Example two](https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile)

The plan is to add this as a similar feature, to make local installation a bit more straightforward.

**Comment by nvanderperren** [comment]
Ok, solved!

**Comment by netsensei** [comment]
I changed this one. See the file `default.config.yml` and the updated explanation in the `README.md` file.
