### ISSUE TITLE
Errors setting up datahub after starting virtualbox

### ISSUE THREAD

**Issue by Lod3** [thedatahub/Datahub-Box#8]
Errors after running
> composer install

Inside Datahub repository, following the installation instructions provided for  [Datahub](https://github.com/thedatahub/Datahub#install) 

> $ composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for alcaeus/mongo-php-adapter 1.1.3 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
>     - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>   Problem 2
>     - Installation request for mongodb/mongodb 1.1.2 -> satisfiable by mongodb/mongodb[1.1.2].
>     - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>   Problem 3
>     - Installation request for sabre/xml 1.5.0 -> satisfiable by sabre/xml[1.5.0].
>     - sabre/xml 1.5.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
>   Problem 4
>     - Installation request for symfony/symfony v2.8.27 -> satisfiable by symfony/symfony[v2.8.27].
>     - symfony/symfony v2.8.27 requires ext-xml * -> the requested PHP extension xml is missing from your system.
>   Problem 5
>     - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].
>     - phpunit/php-code-coverage 4.0.8 requires ext-dom * -> the requested PHP extension dom is missing from your system.
>   Problem 6
>     - Installation request for phpunit/phpunit 5.7.x-dev -> satisfiable by phpunit/phpunit[5.7.x-dev].
>     - phpunit/phpunit 5.7.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
>   Problem 7
>     - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - doctrine/mongodb 1.6.0 requires ext-mongo ^1.6.7 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
>     - Installation request for doctrine/mongodb 1.6.0 -> satisfiable by doctrine/mongodb[1.6.0].
> 
>   To enable extensions, verify that they are enabled in those .ini files:
>     - /etc/php/7.0/cli/php.ini
>     - /etc/php/7.0/cli/conf.d/10-opcache.ini
>     - /etc/php/7.0/cli/conf.d/10-pdo.ini
>     - /etc/php/7.0/cli/conf.d/20-calendar.ini
>     - /etc/php/7.0/cli/conf.d/20-ctype.ini
>     - /etc/php/7.0/cli/conf.d/20-exif.ini
>     - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
>     - /etc/php/7.0/cli/conf.d/20-ftp.ini
>     - /etc/php/7.0/cli/conf.d/20-gettext.ini
>     - /etc/php/7.0/cli/conf.d/20-iconv.ini
>     - /etc/php/7.0/cli/conf.d/20-json.ini
>     - /etc/php/7.0/cli/conf.d/20-phar.ini
>     - /etc/php/7.0/cli/conf.d/20-posix.ini
>     - /etc/php/7.0/cli/conf.d/20-readline.ini
>     - /etc/php/7.0/cli/conf.d/20-shmop.ini
>     - /etc/php/7.0/cli/conf.d/20-sockets.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
>     - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> 
> 

[datahub_post_composer_install-23-11-17.txt](https://github.com/thedatahub/Datahub-Box/files/1499286/datahub_post_composer_install-23-11-17.txt)

**Comment by netsensei** [comment]
Seems like the mongo extension from PECL wasn't installed. Probably the box wasn't provisioned entirely. This should be fixed in more recent versions of the box.

Cleaning out old issues with no follow up. Closing this.
