### ISSUE TITLE
Datahub-Box inaccessible after install. 

### ISSUE THREAD

**Issue by Lod3** [thedatahub/Datahub-Box#9]
"File not found" message when requesting http://datahub.box/ after installing without errors.
Virtualbox shows datahub.box is running, checked the hosts file and it was correctly edited by Vagrant.  

Ubuntu 16.04 LTS.

**Comment by netsensei** [comment]
Did you install the datahub application itself? 

1. git clone the Datahub (github.com/thedatahub/datahub) to the folder you specified in your vagrant_synced_folders in `config.yml`
2. vagrant ssh into your box.
3. cd /vagrant/datahub
3. run composer install, app/console app:setup and app/console doctrine:mongodb:fixtures:load --append 

See also: [https://github.com/thedatahub/Datahub/blob/master/README.md](https://github.com/thedatahub/Datahub/blob/master/README.md)

You will have to follow similar setup for Project Blacklight per [the instructions](https://github.com/VlaamseKunstcollectie/Arthub-Frontend).

**Comment by netsensei** [comment]
Cleaning out old issues with no follow up. Closing this.
